spring:
  application:
    name: config-server
  profiles:
    active: native   #激活本地文件系统，就不用github远程了
  rabbitmq:
    host: 192.168.190.132
    port: 5672
    username: admin
    password: admin
    
#  cloud:  默认的  不配置也行
#    config:
#      server:
#        native:
#          search-locations: classpath:/config

   
    
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Rapide-S/spring-cloud #仓库路径
#          searchPaths: sp-config #苍鹭下的一个子目录，里面放的是配置文件
          #username: your-username
          #password: your-password
    
server:
  port: 6001
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
        
       
        
        

